version: "3"
services:
  web-service:
    image: node:18.12.1
    container_name: $CONTAINER_WEB
    ports:
      - 8080:$NODE_PORT
    environment:
      NODE_ENV: $NODE_ENV
      NODE_DOMAIN_NAME: $NODE_DOMAIN_NAME
      NODE_PORT: $NODE_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: db-service
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      TZ: Asia/Tokyo
    tty: true # コンテナの正常終了を阻止
    depends_on:
      - db-service
    volumes:
      - ./node:$WORKING_DIR
    working_dir: $WORKING_DIR

  db-service:
    image: postgres:13.2
    container_name: $CONTAINER_DB
    ports:
      - 5432:$DB_PORT
    user: root # 特に問題は起きていなかったが、pgadminと同様の対応
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/postgresql/data # 初期起動の際は/db直下の/dataを削除

  # pgadmin-service:
  #   image: dpage/pgadmin4:6.15
  #   container_name: $CONTAINER_PGADMIN
  #   ports:
  #     - 8888:80
  #   user: root # ./pgadminがroot権限で生成されるため
  #   volumes:
  #     - ./pgadmin:/var/lib/pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: test@test.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   depends_on:
  #     - db-service
